t_getopt: t_getopt.o error_functions.o
	gcc t_getopt.o error_functions.o -o t_getopt

t_getopt.o: t_getopt.c
	gcc -c t_getopt.c

error_functions.o: ../lib/error_functions.c
	gcc -c ../lib/error_functions.c
